/* Populate tabla clientes */
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Andrés', 'Guzmán', 'profesor@bolsadeideas.com', '2018-01-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Mr. John', 'Doe', 'john.doe@gmail.com', '2018-01-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Linus', 'Torvalds', 'linus.torvalds@gmail.com', '2018-01-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Rasmus', 'Lerdorf', 'rasmus.lerdorf@gmail.com', '2018-01-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Erich', 'Gamma', 'erich.gamma@gmail.com', '2018-02-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Richard', 'Helm', 'richard.helm@gmail.com', '2018-02-10');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ralph', 'Johnson', 'ralph.johnson@gmail.com', '2018-02-18');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('John', 'Vlissides', 'john.vlissides@gmail.com', '2018-02-28');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Dr. James', 'Gosling', 'james.gosling@gmail.com', '2018-03-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Magma', 'Lee', 'magma.lee@gmail.com', '2018-03-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Tornado', 'Roe', 'tornado.roe@gmail.com', '2018-03-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Jade', 'Doe', 'jane.doe@gmail.com', '2018-03-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Pedro', 'Martínez', 'pedro.martinez@example.com', '2018-04-01');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('María', 'García', 'maria.garcia@example.com', '2018-04-02');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Juan', 'López', 'juan.lopez@example.com', '2018-04-03');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Luisa', 'Hernández', 'luisa.hernandez@example.com', '2018-04-04');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Carlos', 'Gómez', 'carlos.gomez@example.com', '2018-04-05');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Ana', 'Pérez', 'ana.perez@example.com', '2018-04-06');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Elena', 'Fernández', 'elena.fernandez@example.com', '2018-04-07');
INSERT INTO clientes (nombre, apellido, email, create_at) VALUES('Diego', 'Rodríguez', 'diego.rodriguez@example.com', '2018-04-08');